title: WUSTL Formal Theory Workshop
description: A workshop hosted by WUSTL's Political Science Department, for formal theory papers at any stage of development.
list_title: Upcoming Meetings

# Build settings
theme: minima
